name: Cartographer
version: 1.0.0
description: Generate map data with a drag and drop interface
addon_url: https://github.com/AndrewHaine/statamic-cartographer
developer: Andrew Haine
developer_url: https://www.andrewhaine.co.uk
commercial: true
fieldtype_fields:
  mode:
    type: select
    display: Mode
    instructions: Which type of map would you like to use?
    default: google
    options:
      google: Google Maps
      mapbox: Mapbox
  default_center:
    type: array
    width: 50
    keys:
      lat: Lat
      lng: Lng
